### ISSUE TITLE
revamp some design

### ISSUE THREAD

**Issue by kittisak0501** [Nantipak/Final-Project#9]
in every menu page
- change input from text to button
use appetizer in this commit as base :61c9f6cd3c5db0dad6be3de2c05bff91330f119a
note : change `id` in every `<input type="hidden" name="id" style="width:50px;" value="id">` to have the same as name of the menu, ref is in `food.js`

**Comment by auto0032** [comment]
c9cb49093af925f3cb49e7080121e07c4f92456b
adding ID in every menu
